# Redireciona todo HTTP para HTTPS
server {
    listen 80;
    server_name agenday.com www.agenday.com api.agenday.com storage.agenday.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
